### ISSUE TITLE
Add text chat

### ISSUE THREAD

**Issue by HassenMaamri** [dgonzalez21/Node-Chat#1]
Hello, Great work i really like it.. I see you're using simplewebrtc, is it possible to use the same datachannel to allow paired people to have a text conversation option as well? how would you do it?

**Comment by dgonzalez21** [comment]
Yea that wouldn't be that hard. SimpleWebRTC doesn't support text chat currently, but there are plenty of more advanced WebRTC frameworks that do Video + Chat like [RTCMultiConnection](https://github.com/muaz-khan/RTCMultiConnection). I've already setup the framework for managing connections and rooms so all you would have to do is change a couple lines on the frontend.

P.s sorry for the late reply haven't been checking github often cause of school

**Comment by dgonzalez21** [comment]
https://rtcmulticonnection.herokuapp.com/demos/Audio+Video+TextChat+FileSharing.html 

Use the current backend for creating room ID's and closing rooms, but change the frontend to something like this

**Comment by HassenMaamri** [comment]
I will check it out, thank you ;)
